### ISSUE TITLE
Fuukoi: plan for web -> bd

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#97]
To me, this anime is slightly inferior to a few of the other love theme anime you guys have been involved in, but still fun.

A year has passed and I haven’t seen other fansubs actively adapting to Blu-ray. This project has ready-made files on the GitHub repo, which makes it easier to maintain subtitles, so I chose this first.

If you are working on this, please let me know; if you are not currently doing this, I will create a pull request to start work on it.

I will be using IrizaRaws’ BDRip for it.

**Comment by MIRIMIRIM** [comment]
I had already encoded the BDRip for the main epsiodes of *Fuukoi* a year ago, but I haven’t had much motivation to continue making it.

If you want to adapt subtitles to Blu-ray, you need to pay attention to how *IrizaRaw* trimming source because BDMV does not use separate m2ts files for each episode. And I trim it according to the BDMV chapters.

Of course, if you find any issues outside of shift timeline, you can also PR, and I will finally shift them.
